Models/Station.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Test.Models
{
    public class Station
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public ICollection<Come> Comes { get; set; }
        public ICollection<Out> Outs { get; set; }
        public Station()
        {
            Comes = new List<Come>();
            Outs = new List<Out>();
        }
    }
}

Controllers/StationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Models;

namespace Test.Controllers
{
    public class StationController : Controller
    {
        ModelContext db = new ModelContext();

        public ActionResult Index() {

            IEnumerable<Station> stations = db.Stations;

            ViewBag.Station = stations;

            return View();
        }

        [HttpGet]
        public ActionResult Change(int? Id) {

            if (Id == null)
            {
                return HttpNotFound();
            }
            Station station = db.Stations.Find(Id);
            if (station != null) 
            {                
                return View(station);
            }            
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Change(Station station) {

            Station trainDb = db.Stations.FirstOrDefault(s => s.Name == station.Name && s.Id != station.Id);
            if (station == null)
            {
                ModelState.AddModelError("", "Все поля должны быть заполнены");
            }
            if (trainDb != null)
            {
                ModelState.AddModelError("", "Такая станция уже есть");
            }
            if (ModelState.IsValid)
            {
                db.Entry(station).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(station);
        }

        [HttpGet]
        public ActionResult GreateStation()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GreateStation(Station station)
        {
            Station trainDb = db.Stations.FirstOrDefault(s => s.Name == station.Name);
            if (station == null)
            {
                ModelState.AddModelError("", "Все поля должны быть заполнены");
            }
            if (trainDb != null)
            {
                ModelState.AddModelError("", "Такая станция уже есть");
            }
            if (ModelState.IsValid)
            {
                db.Stations.Add(station);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(station);
                       
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            // Station s = db.Stations.Find(id);
            Station s = db.Stations
                .Include(st => st.Comes)
                .Include(st => st.Outs)
                .FirstOrDefault(st => st.Id == id);
            if (s == null)
            {
                return HttpNotFound();
            }           
            db.Stations.Remove(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

Views/Station/Change.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model  Test.Models.Station

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Change</title>
</head>
<body>
    @using (Html.BeginForm("Change", "Station", FormMethod.Post))
    {@Html.ValidationSummary()
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.Name, "Имя станции")
            <br />
            @Html.EditorFor(m => m.Name)
        </p>
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Station/GreateStation.cshtml
@model Test.Models.Station

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GreateStation</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>Station</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Station/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home Station";
}


    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Станции</title>
    </head>
    <body>
        <div>
            <h3>Станции</h3>
            <p><a href="/Station/GreateStation/">Создать станцию</a></p>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"><p>Название станции</p></th>
                        <th scope="col">#</th>
                        <th scope="col">#</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var b in ViewBag.Station)
                    {
                        <tr>
                            <td><p>@b.Name</p></td>
                            <td><p><a href="/Station/Change/@b.Id">Изменить</a></p></td>
                            <td><p><a href="/Station/Delete/@b.Id">Удалить</a></p></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </body>
    </html>